### ISSUE TITLE
Program is inoperable

### ISSUE THREAD

**Issue by Browningate** [yousefkotp/Movies-and-Series-Scraper#2]
Any attempts to search for movies or shows leads to an "unhandled exception" error, at least in the Windows version:

"Traceback (most recent call last):
  File "Movies & Series Scraper.py", line 84, in <module>
ValueError: invalid literal for int() with base 10: ''
[7068] Failed to execute script 'Movies & Series Scraper' due to unhandled exception!"

**Comment by yousefkotp** [comment]
you should enter the number corresponding to the movie, not the name of the movie itself!

**Comment by Browningate** [comment]
No movies or shows are ever listed after entering the name, so the numbers are meaningless.

**Comment by yousefkotp** [comment]
Could you give me a sample for the input you entered?

**Comment by Browningate** [comment]
>
For shows, I tried "House," "The Good Guys," "Early Edition," "The Strain," "Seinfeld," and others. For movies, I tried "2000 Mules," "22 Jump Street," "The Transporter," "Inception," and others.

**Comment by yousefkotp** [comment]
Firstly make sure you are connected to the internet, secondly if you are using .py instead of .exe, install the libraries imported in the beginning of the python file

**Comment by Browningate** [comment]
> Firstly make sure you are connected to the internet, secondly if you are using .py instead of .exe, install the libraries imported in the beginning of the python file

I'm definitely connected to the Internet, and using the .exe.

**Comment by yousefkotp** [comment]
Kindly provide info about the OS you are using, also check if your keyboard is EN-US

**Comment by Browningate** [comment]
> Kindly provide info about the OS you are using, also check if your keyboard is EN-US

It is. Windows 10, build 19044.

**Comment by yousefkotp** [comment]
Are you sure you typed the name as "The House" without using commas or dot at the end or quotation marks?

**Comment by Browningate** [comment]
The show is just called "House." I included no punctuation for any of the search queries.

**Comment by yousefkotp** [comment]
could you provide a screenshot or video for the process?

**Comment by Browningate** [comment]
> could you provide a screenshot or video for the process?

Yes.
![downloader-tool-troubleshooting-9-2022](https://user-images.githubusercontent.com/96092066/188280517-0013e60d-a92d-4ef3-8f95-874729879675.PNG)

**Comment by yousefkotp** [comment]
Try running from cmd instead of powershell, also you have to move the exe file from "Temp" folder, try putting it in Desktop for example

**Comment by Browningate** [comment]
> Try running from cmd instead of powershell, also you have to move the exe file from "Temp" folder, try putting it in Desktop for example

Same problem occurs.

**Comment by yousefkotp** [comment]
One last thing, try running it as an administrator.

**Comment by Browningate** [comment]
> One last thing, try running it as an administrator.

Why exactly would it require administrative clearance to run?

**Comment by yousefkotp** [comment]
I have ran out of options and this is the only one remaining, if you don't want to run just don't!. The program works fine everywhere except on your device for unknown reason.
