### ISSUE TITLE
Series print out on a list instead of opening

### ISSUE THREAD

**Issue by paulwababu** [yousefkotp/Movies-and-Series-Scraper#4]
Great job on this bro. My question is how do I get a list of all urls for a series in a list? I don't want the urls for the series to open up on browser but to print out the first episode to the last.
Thanks

**Comment by yousefkotp** [comment]
Starting from line 63 to 70, you will find the following code:
```python
 while counter_episodes >= ep1:      # Iterating through desired episodes
        html_page = requests.get(episodes_links[counter_episodes-1].get("href"))
        soup = BeautifulSoup(html_page.content, "lxml")
        link = soup.find("iframe",{"name":"watch"})
        watching_link = link.get("data-lazy-src")
        result = requests.get(watching_link)
        webbrowser.open(watching_link)
        counter_episodes -= 1
```
The "watching_link" variable holds the link for the series episodes, you can remove the "webbrowser.open" and replace it with print.
